name = "viralink"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = ".next"

# Environment variables
[env.production.vars]
NODE_ENV = "production"

[env.preview.vars]
NODE_ENV = "preview"

[env.development.vars]
NODE_ENV = "development"

# D1 Database bindings
[[env.production.d1_databases]]
binding = "DB"
database_name = "viralink-prod"
database_id = "your-production-database-id"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "viralink-preview"
database_id = "your-preview-database-id"

[[env.development.d1_databases]]
binding = "DB"
database_name = "viralink-dev"
database_id = "your-development-database-id"

# Analytics
[env.production.analytics]
enabled = true

[env.preview.analytics]
enabled = true

# Build configuration
[build]
command = "npm run build"

# Functions configuration for API routes
[functions]
node_compat = true

# KV namespaces (if needed for caching)
# [[env.production.kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# R2 buckets (if needed for file storage)
# [[env.production.r2_buckets]]
# binding = "UPLOADS"
# bucket_name = "viralink-uploads"
# preview_bucket_name = "viralink-uploads-preview"